// Quill's own prompts, in batches. Each batch is added to your _Prompts.md
// once; a later batch adds only prompts that aren't already there, so ones
// you've deleted or used never come back. To add more, append a new batch.

export const PROMPT_BATCHES: string[][] = [
  [
    // Places and atmosphere
    'Write a short, atmospheric vignette set in a laundromat at 3 a.m., where one machine is still running.',
    'Describe a lighthouse the night after its keeper retires.',
    'A greenhouse in winter: write what grows there, and who tends it.',
    'Set a scene in a hotel lobby during a power outage, lit only by phones and one candle.',
    'Write about a diner that has been open every day for forty years, on the night it closes.',
    'Describe an attic where every object belongs to someone who has died, from the point of view of the dust.',
    'A train station in a town the railway no longer serves. Someone is waiting anyway.',
    'Write a vignette set inside a bakery an hour before it opens.',
    'Describe a small-town library after a flood has receded.',
    'An empty swimming pool at the end of summer. Write who climbs down into it.',
    'Set a scene in a bookshop that only opens when it rains.',
    'Write about a rooftop garden in the middle of a city, seen at dawn.',
    'A ferry crossing in thick fog. The foghorn is the only clock.',
    'Describe a closed-down amusement park from the inside of the ticket booth.',
    'Write a vignette set in a clock repair shop where every clock tells a different time.',
    'A cabin in the woods with a guestbook going back sixty years. Write the last entry.',
    'Describe a hospital waiting room at midnight without naming anyone’s illness.',
    'Set a scene in a record store during the last hour of its closing-down sale.',
    'Write about a church that has been turned into apartments, and the one tenant who still kneels.',
    'A motel pool, neon sign buzzing, one swimmer doing slow laps.',
    'Describe a market at the moment the stalls are packing up.',
    'Write about an observatory on the one clear night of the year.',
    'An underground parking garage where a car alarm has been going for an hour.',
    'Set a vignette in a lost-and-found office. Choose one object and tell its story.',
    'Describe a beach town in February, when every shop is shuttered but one.',
    'Write a scene inside a snow globe, from the point of view of the tiny figure.',
    'A school hallway on the first day of summer vacation.',
    'Describe a kitchen during a family argument, focusing only on the food.',
    'Write about a lookout tower where a ranger has spent the season alone.',
    'A late-night bus with three passengers who don’t speak.',
    'Describe a museum after closing, when the night guard makes one last round.',
    'Set a scene in a flower shop the morning of a funeral and a wedding.',
    'Write a vignette about a porch at the end of a long drought, the first night it rains.',
    'A post office in a village of two hundred people. Write the day’s mail.',
    'Describe a pawn shop through the objects in its front window.',
    'Write about a boat that has been tied to the same dock for thirty years.',
    'A hedge maze at dusk. Someone is humming inside it.',
    'Describe an airport gate after the last flight has been cancelled.',
    'Set a scene in a tailor’s shop where the suits were never collected.',
    'Write about a well in a courtyard, and what the neighbors throw into it.',

    // Characters
    'Write about a locksmith who has never been able to open one particular door.',
    'A retired magician still practices every morning for an audience of none.',
    'Write a character who collects other people’s grocery lists.',
    'Someone keeps receiving postcards from a city they have never visited.',
    'Write about a translator who realizes they have been mistranslating one word for years.',
    'A night-shift nurse knows every patient by the sound of their call button.',
    'Write about a piano tuner who can’t play.',
    'A child is convinced the neighbor is a retired astronaut. Write the day they find out.',
    'Write about a mapmaker hired to chart a town that keeps changing.',
    'A woman inherits a houseplant with a list of instructions forty pages long.',
    'Write about a lighthouse keeper’s daughter who has never seen a ship.',
    'A man takes the same bus every day to a stop where he never gets off.',
    'Write a character who apologizes to objects when they drop them.',
    'Someone works as a professional mourner. Write the funeral that finally makes them cry.',
    'Write about a beekeeper the week the hives go quiet.',
    'A cartographer’s apprentice finds an island on the map that isn’t in the sea.',
    'Write about a school janitor who knows every secret in the building.',
    'An old boxer teaches a child to skip rope.',
    'Write about a woman who talks to her late husband through the crossword.',
    'A radio DJ is certain only one person is listening. Write who it is.',
    'Write a character who has never once been late, on the day they are.',
    'Someone restores old photographs and finds themselves in one from 1920.',
    'Write about a chef who has lost their sense of taste.',
    'A mail carrier delivers the same letter every day for a week. It has no address.',
    'Write about a tour guide in a town where nothing ever happened.',
    'Two strangers share an umbrella for three blocks. Write both of their thoughts.',
    'Write about an elevator operator in the last building that still has one.',
    'A calligrapher is asked to write a letter they would never send.',
    'Write about someone who sleeps with the lights on, and why.',
    'A sailor comes home to a town that has moved inland.',

    // What if
    'What if every lie you told appeared as a small bruise? Write one ordinary day.',
    'What if the moon stopped rising? Write the first night without it, from a single porch.',
    'What if you could hear the last song someone listened to by touching their hand?',
    'What if the town’s church bells rang once for every secret kept that day?',
    'What if shadows went missing one morning, starting with yours?',
    'What if your reflection started arriving a second late?',
    'What if everyone could see how many days they had left, except you?',
    'What if the streetlights on your street went out in the order people fell asleep?',
    'What if books rewrote their endings when no one was reading them?',
    'What if you found a door in your home that wasn’t there yesterday?',
    'What if the sea went out one morning and didn’t come back?',
    'What if the weather followed your mood, and you had to go to a wedding?',
    'What if your childhood home still had your family in it, just as they were?',
    'What if photographs aged along with the people in them?',
    'What if every clock in the world stopped, except the one in your kitchen?',
    'What if you could borrow a stranger’s memory for a day?',
    'What if letters arrived on the date they were meant to be read, even decades later?',
    'What if the last person to see a star before dawn got to keep it?',
    'What if you woke up fluent in a language no one else speaks?',
    'What if the rain carried the smell of wherever it had fallen before?',
    'What if the dead could send one text message a year?',
    'What if your house remembered everyone who ever lived in it, and told you at night?',
    'What if a bookstore sold unwritten books, and you could choose one?',
    'What if the wind could be caught in jars, and someone was selling them?',
    'What if you could only speak in questions for one day?',

    // Dialogue
    'Write a conversation between two people waiting for the same person who isn’t coming.',
    'Write a scene told entirely through a phone call where one person is lying.',
    'Two old friends meet after twenty years and only talk about the weather. Show what they mean.',
    'Write an argument about how to load a dishwasher that is really about something else.',
    'A child asks a grandparent a question the grandparent has avoided their whole life.',
    'Write a job interview where the interviewer is the one who needs the job.',
    'Two strangers are stuck in an elevator. One of them knows the other.',
    'Write a breakup conversation that takes place entirely in a hardware store.',
    'A ghost and the new homeowner negotiate the thermostat.',
    'Write a conversation where neither person says the word they are both thinking.',
    'Two siblings clean out their parents’ house and argue over a single spoon.',
    'Write a first date where both people are pretending to be someone else.',
    'A detective interviews a witness who only answers in stories.',
    'Write the conversation a couple has in the car after a dinner party.',
    'Two night-shift workers talk on their break about what they would do with a day off.',

    // Memory and essay
    'Write about a kitchen you remember better than your own face.',
    'Describe the first time you realized an adult didn’t know what they were doing.',
    'Write about a smell that can take you back twenty years in one second.',
    'Write about a song that belongs to someone you no longer talk to.',
    'Describe a place you have only been to once but think about often.',
    'Write about something you were sure of at twelve that turned out to be wrong.',
    'Write about the best meal you have ever had, and what it had to do with the people.',
    'Describe a teacher who changed something in you, without naming the subject they taught.',
    'Write about a time you were lost, literally or otherwise.',
    'Write about the object you would grab first in a fire, and why it isn’t the obvious one.',
    'Describe a view from a window you used to look out of every day.',
    'Write about a habit you inherited without meaning to.',
    'Write about a road trip, told only through the things you ate.',
    'Describe your hometown to someone who will never visit it.',
    'Write about a gift you gave that meant more to you than to them.',
    'Write about the quietest place you have ever been.',
    'Describe a time you changed your mind about someone.',
    'Write about a rule in your family that no one ever said out loud.',
    'Write about a piece of clothing you kept long after it stopped fitting.',
    'Describe the moment you knew a friendship was over.',
    'Write an essay about why you write, without using the word “write.”',
    'Write about a book you read at exactly the right time.',
    'Describe a small ritual that gets you through hard weeks.',
    'Write about a place that no longer exists except in your memory.',
    'Write about a sound from your childhood you haven’t heard in years.',
    'Write about the kind of person you pretend to be at parties.',
    'Describe a storm you remember, and who you were with.',
    'Write about an ordinary Tuesday you would like to live again.',
    'Write about something you are learning slowly.',
    'Write a letter to the house you grew up in.',

    // Sensory and craft
    'Describe a thunderstorm using only sounds.',
    'Write a scene in which the main character never sees anything: only smell, touch and sound.',
    'Describe the color blue to someone who has never seen it.',
    'Write a vignette where the weather is the main character.',
    'Describe a crowded room through the feet of the people in it.',
    'Write about a meal so vividly the reader gets hungry.',
    'Describe winter without using the words cold, snow or ice.',
    'Write a scene that takes place in the ten seconds before a glass hits the floor.',
    'Describe a city at night through the windows that are still lit.',
    'Write about a room by describing only what is missing from it.',
    'Describe a forest after a fire, focusing on what is starting to grow.',
    'Write a scene in which a single candle is the only light, and it is burning down.',
    'Describe a person entirely through their hands.',
    'Write a vignette about fog rolling into a harbor town, street by street.',
    'Describe a summer afternoon so slow that time feels thick.',

    // Constraints
    'Write a story in exactly 100 words about a key that fits no lock.',
    'Write a scene without using the letter “e” for the first paragraph.',
    'Tell a whole story in six sentences, each one starting with the same word.',
    'Write a story in the form of a recipe.',
    'Write a vignette in the second person: “You open the door…”',
    'Write a story told backward, from the last moment to the first.',
    'Write a story in the form of a list of things left in a rental car.',
    'Write a love story in the form of a weather forecast.',
    'Write a scene in which every sentence is a question.',
    'Tell a story through the notes someone leaves on the fridge over a year.',
    'Write a ghost story set entirely in daylight.',
    'Write a story in the form of an instruction manual for something that can’t be assembled.',
    'Write a 300-word story that ends with the line “and the lights came back on.”',
    'Write a story that begins with the line “Nobody ever used the side door.”',
    'Start with “The letter was addressed to me, but it was forty years too late.”',
    'Start with “It was the kind of town where the clocks all ran a little slow.”',
    'Start with “I found the photograph in a library book.”',
    'Start with “The last customer of the night ordered something we didn’t serve.”',
    'End your story with “She never did tell anyone about the lighthouse.”',
    'Start with “Every Sunday, my grandfather set a place at the table for someone who never came.”',
    'Write a story in the form of a museum placard for an ordinary object.',
    'Write a story told through five voicemails.',
    'Write a scene using only dialogue, with no tags or descriptions.',
    'Write a piece that is exactly one sentence long, but a full page.',
    'Write a story in which the narrator is the house.',

    // Objects
    'An old key is found sewn into the lining of a coat. Write where it leads.',
    'Write about a music box that plays a song no one recognizes.',
    'A typewriter in a thrift store has a half-finished letter still in it.',
    'Write about a compass that doesn’t point north. It points toward something else.',
    'A pair of worn ballet shoes hangs from a nail in a barn. Write their story.',
    'Write about a jar of buttons and the clothes they came from.',
    'A pocket watch is engraved with a date that hasn’t happened yet.',
    'Write about a quilt made from the clothes of three generations.',
    'An unmarked cassette tape turns up in a used car.',
    'Write about a chair no one in the family is allowed to sit in.',
    'A snow globe from a town that doesn’t exist.',
    'Write about a recipe card with a stain on it, and the night that stain happened.',
    'A matchbook from a hotel that burned down.',
    'Write about a map with a circle drawn on it in red ink and no explanation.',
    'A hand-knitted sweater arrives in the mail with no return address.',
    'Write about a telescope pointed permanently at one neighbor’s window.',
    'A bell hangs over the door of a shop that closed years ago. It still rings.',
    'Write about a glass eye kept in a velvet box.',
    'An old ledger records debts paid in favors, not money.',
    'Write about a lantern that only lights when someone is lying.',

    // Seasons and time
    'Write about the first cold morning of autumn in a town that depends on tourists.',
    'Describe New Year’s Eve from the point of view of someone working the night shift.',
    'Write about a family’s last summer at a lake house before it’s sold.',
    'Write about the longest day of the year in a place where the sun barely sets.',
    'Describe a small town on the morning after its biggest festival.',
    'Write about a birthday that no one remembers except the one who has it.',
    'Write about the week between Christmas and New Year, when no one knows what day it is.',
    'Describe the first warm day of spring in a city that has been grey for months.',
    'Write about Halloween night from the point of view of the house everyone skips.',
    'Write about a harvest in a year when nothing grew right.',
    'Write about the hour after a long-awaited phone call.',
    'Describe the last day of a job someone held for thirty years.',
    'Write about a Sunday afternoon that stretches on forever.',
    'Write about the moment a storm passes and everyone steps outside.',
    'Describe the night before a big move, in an apartment full of boxes.',

    // Small mysteries
    'Every morning, someone leaves a single flower on the same park bench. Write who.',
    'A neighbor’s porch light has been on for three weeks straight.',
    'Write about a town where every house has one bricked-up window.',
    'Someone keeps rearranging the books in a library into a message.',
    'A dog shows up at the same café every day at noon, then leaves at one.',
    'Write about a phone booth that still rings, though it was disconnected years ago.',
    'Every clock in an antique shop stops at the same minute each night.',
    'A mysterious tenant pays rent in handwritten poems.',
    'Write about a painting in a hotel hallway that changes slightly each week.',
    'A trail of chalk arrows appears on the sidewalk overnight.',
    'Someone has been leaving the same crossword clue in the town paper for ten years.',
    'Write about a garden that blooms only on the anniversary of a death.',
    'A woman finds her own handwriting in a stranger’s diary.',
    'Write about a radio station that plays only at 2 a.m., for exactly one hour.',
    'The town’s oldest resident insists the river used to run the other way.',
  ],
];
