// Quill's own prompts, in batches. Each batch is added to your _Prompts.md
// once; a later batch adds only prompts that aren't already there, so ones
// you've deleted or used never come back. To add more, append a new batch.

export const PROMPT_BATCHES: string[][] = [
  [
    // Places and atmosphere
    'Write a short, atmospheric vignette set in a laundromat at 3 a.m., where one machine is still running.',
    'Describe a lighthouse the night after its keeper retires.',
    'A greenhouse in winter: write what grows there, and who tends it.',
    'Set a scene in a hotel lobby during a power outage, lit only by phones and one candle.',
    'Write about a diner that has been open every day for forty years, on the night it closes.',
    'Describe an attic where every object belongs to someone who has died, from the point of view of the dust.',
    'A train station in a town the railway no longer serves. Someone is waiting anyway.',
    'Write a vignette set inside a bakery an hour before it opens.',
    'Describe a small-town library after a flood has receded.',
    'An empty swimming pool at the end of summer. Write who climbs down into it.',
    'Set a scene in a bookshop that only opens when it rains.',
    'Write about a rooftop garden in the middle of a city, seen at dawn.',
    'A ferry crossing in thick fog. The foghorn is the only clock.',
    'Describe a closed-down amusement park from the inside of the ticket booth.',
    'Write a vignette set in a clock repair shop where every clock tells a different time.',
    'A cabin in the woods with a guestbook going back sixty years. Write the last entry.',
    'Describe a hospital waiting room at midnight without naming anyone’s illness.',
    'Set a scene in a record store during the last hour of its closing-down sale.',
    'Write about a church that has been turned into apartments, and the one tenant who still kneels.',
    'A motel pool, neon sign buzzing, one swimmer doing slow laps.',
    'Describe a market at the moment the stalls are packing up.',
    'Write about an observatory on the one clear night of the year.',
    'An underground parking garage where a car alarm has been going for an hour.',
    'Set a vignette in a lost-and-found office. Choose one object and tell its story.',
    'Describe a beach town in February, when every shop is shuttered but one.',
    'Write a scene inside a snow globe, from the point of view of the tiny figure.',
    'A school hallway on the first day of summer vacation.',
    'Describe a kitchen during a family argument, focusing only on the food.',
    'Write about a lookout tower where a ranger has spent the season alone.',
    'A late-night bus with three passengers who don’t speak.',
    'Describe a museum after closing, when the night guard makes one last round.',
    'Set a scene in a flower shop the morning of a funeral and a wedding.',
    'Write a vignette about a porch at the end of a long drought, the first night it rains.',
    'A post office in a village of two hundred people. Write the day’s mail.',
    'Describe a pawn shop through the objects in its front window.',
    'Write about a boat that has been tied to the same dock for thirty years.',
    'A hedge maze at dusk. Someone is humming inside it.',
    'Describe an airport gate after the last flight has been cancelled.',
    'Set a scene in a tailor’s shop where the suits were never collected.',
    'Write about a well in a courtyard, and what the neighbors throw into it.',

    // Characters
    'Write about a locksmith who has never been able to open one particular door.',
    'A retired magician still practices every morning for an audience of none.',
    'Write a character who collects other people’s grocery lists.',
    'Someone keeps receiving postcards from a city they have never visited.',
    'Write about a translator who realizes they have been mistranslating one word for years.',
    'A night-shift nurse knows every patient by the sound of their call button.',
    'Write about a piano tuner who can’t play.',
    'A child is convinced the neighbor is a retired astronaut. Write the day they find out.',
    'Write about a mapmaker hired to chart a town that keeps changing.',
    'A woman inherits a houseplant with a list of instructions forty pages long.',
    'Write about a lighthouse keeper’s daughter who has never seen a ship.',
    'A man takes the same bus every day to a stop where he never gets off.',
    'Write a character who apologizes to objects when they drop them.',
    'Someone works as a professional mourner. Write the funeral that finally makes them cry.',
    'Write about a beekeeper the week the hives go quiet.',
    'A cartographer’s apprentice finds an island on the map that isn’t in the sea.',
    'Write about a school janitor who knows every secret in the building.',
    'An old boxer teaches a child to skip rope.',
    'Write about a woman who talks to her late husband through the crossword.',
    'A radio DJ is certain only one person is listening. Write who it is.',
    'Write a character who has never once been late, on the day they are.',
    'Someone restores old photographs and finds themselves in one from 1920.',
    'Write about a chef who has lost their sense of taste.',
    'A mail carrier delivers the same letter every day for a week. It has no address.',
    'Write about a tour guide in a town where nothing ever happened.',
    'Two strangers share an umbrella for three blocks. Write both of their thoughts.',
    'Write about an elevator operator in the last building that still has one.',
    'A calligrapher is asked to write a letter they would never send.',
    'Write about someone who sleeps with the lights on, and why.',
    'A sailor comes home to a town that has moved inland.',

    // What if
    'What if every lie you told appeared as a small bruise? Write one ordinary day.',
    'What if the moon stopped rising? Write the first night without it, from a single porch.',
    'What if you could hear the last song someone listened to by touching their hand?',
    'What if the town’s church bells rang once for every secret kept that day?',
    'What if shadows went missing one morning, starting with yours?',
    'What if your reflection started arriving a second late?',
    'What if everyone could see how many days they had left, except you?',
    'What if the streetlights on your street went out in the order people fell asleep?',
    'What if books rewrote their endings when no one was reading them?',
    'What if you found a door in your home that wasn’t there yesterday?',
    'What if the sea went out one morning and didn’t come back?',
    'What if the weather followed your mood, and you had to go to a wedding?',
    'What if your childhood home still had your family in it, just as they were?',
    'What if photographs aged along with the people in them?',
    'What if every clock in the world stopped, except the one in your kitchen?',
    'What if you could borrow a stranger’s memory for a day?',
    'What if letters arrived on the date they were meant to be read, even decades later?',
    'What if the last person to see a star before dawn got to keep it?',
    'What if you woke up fluent in a language no one else speaks?',
    'What if the rain carried the smell of wherever it had fallen before?',
    'What if the dead could send one text message a year?',
    'What if your house remembered everyone who ever lived in it, and told you at night?',
    'What if a bookstore sold unwritten books, and you could choose one?',
    'What if the wind could be caught in jars, and someone was selling them?',
    'What if you could only speak in questions for one day?',

    // Dialogue
    'Write a conversation between two people waiting for the same person who isn’t coming.',
    'Write a scene told entirely through a phone call where one person is lying.',
    'Two old friends meet after twenty years and only talk about the weather. Show what they mean.',
    'Write an argument about how to load a dishwasher that is really about something else.',
    'A child asks a grandparent a question the grandparent has avoided their whole life.',
    'Write a job interview where the interviewer is the one who needs the job.',
    'Two strangers are stuck in an elevator. One of them knows the other.',
    'Write a breakup conversation that takes place entirely in a hardware store.',
    'A ghost and the new homeowner negotiate the thermostat.',
    'Write a conversation where neither person says the word they are both thinking.',
    'Two siblings clean out their parents’ house and argue over a single spoon.',
    'Write a first date where both people are pretending to be someone else.',
    'A detective interviews a witness who only answers in stories.',
    'Write the conversation a couple has in the car after a dinner party.',
    'Two night-shift workers talk on their break about what they would do with a day off.',

    // Memory and essay
    'Write about a kitchen you remember better than your own face.',
    'Describe the first time you realized an adult didn’t know what they were doing.',
    'Write about a smell that can take you back twenty years in one second.',
    'Write about a song that belongs to someone you no longer talk to.',
    'Describe a place you have only been to once but think about often.',
    'Write about something you were sure of at twelve that turned out to be wrong.',
    'Write about the best meal you have ever had, and what it had to do with the people.',
    'Describe a teacher who changed something in you, without naming the subject they taught.',
    'Write about a time you were lost, literally or otherwise.',
    'Write about the object you would grab first in a fire, and why it isn’t the obvious one.',
    'Describe a view from a window you used to look out of every day.',
    'Write about a habit you inherited without meaning to.',
    'Write about a road trip, told only through the things you ate.',
    'Describe your hometown to someone who will never visit it.',
    'Write about a gift you gave that meant more to you than to them.',
    'Write about the quietest place you have ever been.',
    'Describe a time you changed your mind about someone.',
    'Write about a rule in your family that no one ever said out loud.',
    'Write about a piece of clothing you kept long after it stopped fitting.',
    'Describe the moment you knew a friendship was over.',
    'Write an essay about why you write, without using the word “write.”',
    'Write about a book you read at exactly the right time.',
    'Describe a small ritual that gets you through hard weeks.',
    'Write about a place that no longer exists except in your memory.',
    'Write about a sound from your childhood you haven’t heard in years.',
    'Write about the kind of person you pretend to be at parties.',
    'Describe a storm you remember, and who you were with.',
    'Write about an ordinary Tuesday you would like to live again.',
    'Write about something you are learning slowly.',
    'Write a letter to the house you grew up in.',

    // Sensory and craft
    'Describe a thunderstorm using only sounds.',
    'Write a scene in which the main character never sees anything: only smell, touch and sound.',
    'Describe the color blue to someone who has never seen it.',
    'Write a vignette where the weather is the main character.',
    'Describe a crowded room through the feet of the people in it.',
    'Write about a meal so vividly the reader gets hungry.',
    'Describe winter without using the words cold, snow or ice.',
    'Write a scene that takes place in the ten seconds before a glass hits the floor.',
    'Describe a city at night through the windows that are still lit.',
    'Write about a room by describing only what is missing from it.',
    'Describe a forest after a fire, focusing on what is starting to grow.',
    'Write a scene in which a single candle is the only light, and it is burning down.',
    'Describe a person entirely through their hands.',
    'Write a vignette about fog rolling into a harbor town, street by street.',
    'Describe a summer afternoon so slow that time feels thick.',

    // Constraints
    'Write a story in exactly 100 words about a key that fits no lock.',
    'Write a scene without using the letter “e” for the first paragraph.',
    'Tell a whole story in six sentences, each one starting with the same word.',
    'Write a story in the form of a recipe.',
    'Write a vignette in the second person: “You open the door…”',
    'Write a story told backward, from the last moment to the first.',
    'Write a story in the form of a list of things left in a rental car.',
    'Write a love story in the form of a weather forecast.',
    'Write a scene in which every sentence is a question.',
    'Tell a story through the notes someone leaves on the fridge over a year.',
    'Write a ghost story set entirely in daylight.',
    'Write a story in the form of an instruction manual for something that can’t be assembled.',
    'Write a 300-word story that ends with the line “and the lights came back on.”',
    'Write a story that begins with the line “Nobody ever used the side door.”',
    'Start with “The letter was addressed to me, but it was forty years too late.”',
    'Start with “It was the kind of town where the clocks all ran a little slow.”',
    'Start with “I found the photograph in a library book.”',
    'Start with “The last customer of the night ordered something we didn’t serve.”',
    'End your story with “She never did tell anyone about the lighthouse.”',
    'Start with “Every Sunday, my grandfather set a place at the table for someone who never came.”',
    'Write a story in the form of a museum placard for an ordinary object.',
    'Write a story told through five voicemails.',
    'Write a scene using only dialogue, with no tags or descriptions.',
    'Write a piece that is exactly one sentence long, but a full page.',
    'Write a story in which the narrator is the house.',

    // Objects
    'An old key is found sewn into the lining of a coat. Write where it leads.',
    'Write about a music box that plays a song no one recognizes.',
    'A typewriter in a thrift store has a half-finished letter still in it.',
    'Write about a compass that doesn’t point north. It points toward something else.',
    'A pair of worn ballet shoes hangs from a nail in a barn. Write their story.',
    'Write about a jar of buttons and the clothes they came from.',
    'A pocket watch is engraved with a date that hasn’t happened yet.',
    'Write about a quilt made from the clothes of three generations.',
    'An unmarked cassette tape turns up in a used car.',
    'Write about a chair no one in the family is allowed to sit in.',
    'A snow globe from a town that doesn’t exist.',
    'Write about a recipe card with a stain on it, and the night that stain happened.',
    'A matchbook from a hotel that burned down.',
    'Write about a map with a circle drawn on it in red ink and no explanation.',
    'A hand-knitted sweater arrives in the mail with no return address.',
    'Write about a telescope pointed permanently at one neighbor’s window.',
    'A bell hangs over the door of a shop that closed years ago. It still rings.',
    'Write about a glass eye kept in a velvet box.',
    'An old ledger records debts paid in favors, not money.',
    'Write about a lantern that only lights when someone is lying.',

    // Seasons and time
    'Write about the first cold morning of autumn in a town that depends on tourists.',
    'Describe New Year’s Eve from the point of view of someone working the night shift.',
    'Write about a family’s last summer at a lake house before it’s sold.',
    'Write about the longest day of the year in a place where the sun barely sets.',
    'Describe a small town on the morning after its biggest festival.',
    'Write about a birthday that no one remembers except the one who has it.',
    'Write about the week between Christmas and New Year, when no one knows what day it is.',
    'Describe the first warm day of spring in a city that has been grey for months.',
    'Write about Halloween night from the point of view of the house everyone skips.',
    'Write about a harvest in a year when nothing grew right.',
    'Write about the hour after a long-awaited phone call.',
    'Describe the last day of a job someone held for thirty years.',
    'Write about a Sunday afternoon that stretches on forever.',
    'Write about the moment a storm passes and everyone steps outside.',
    'Describe the night before a big move, in an apartment full of boxes.',

    // Small mysteries
    'Every morning, someone leaves a single flower on the same park bench. Write who.',
    'A neighbor’s porch light has been on for three weeks straight.',
    'Write about a town where every house has one bricked-up window.',
    'Someone keeps rearranging the books in a library into a message.',
    'A dog shows up at the same café every day at noon, then leaves at one.',
    'Write about a phone booth that still rings, though it was disconnected years ago.',
    'Every clock in an antique shop stops at the same minute each night.',
    'A mysterious tenant pays rent in handwritten poems.',
    'Write about a painting in a hotel hallway that changes slightly each week.',
    'A trail of chalk arrows appears on the sidewalk overnight.',
    'Someone has been leaving the same crossword clue in the town paper for ten years.',
    'Write about a garden that blooms only on the anniversary of a death.',
    'A woman finds her own handwriting in a stranger’s diary.',
    'Write about a radio station that plays only at 2 a.m., for exactly one hour.',
    'The town’s oldest resident insists the river used to run the other way.',
  ],
  // Batch 2: prompts with a title and some direction (Vibe, Anchor, Aim).
  [
    // Mystery and unease
    '**The Saved Voicemail** — Write a 200–400 word first-person vignette about a voicemail you’ve kept for years and finally play again. Vibe: quiet, aching, a little eerie. Anchor: stay with sound: the automated voice, the pause before they speak, what’s audible in the background. Aim: the reader hears the voice themselves.',
    '**Room 14** — A motel housekeeper finds a room that has been made up perfectly, though no one checked in. Write 300–500 words in close third person. Vibe: fluorescent calm with something underneath. Anchor: every detail is ordinary; only one is wrong, and you never explain it. Aim: the reader keeps going back to that one detail.',
    '**The Neighbor’s Light** — For eleven years the house across the street has turned on its porch light at 9:15. Tonight it doesn’t. Write 250–400 words. Vibe: small-town stillness. Anchor: the narrator never crosses the street. Aim: a story built entirely out of watching.',
    '**Return to Sender** — A letter arrives addressed to you, in your own handwriting, postmarked twenty years ago. Write the scene of opening it, 300–500 words. Vibe: uncanny but tender. Anchor: we only see a few lines of the letter. Aim: the reader wants the rest of it.',
    '**The Last Stop** — A night bus driver notices the same passenger has ridden the whole route three times without getting off. Write 300–600 words. Vibe: late-night hum and tired kindness. Anchor: tell it through what the driver sees in the mirror. Aim: an ending that’s either chilling or moving, and you decide which in the last line.',
    '**Inventory** — Write a mystery told only as a list of items found in a stranger’s locker, each with a one-line note. 15–25 items. Vibe: dry, procedural, slowly unsettling. Anchor: no narration outside the list. Aim: the reader pieces together a whole life, and one secret.',
    '**Snow Day** — A town wakes up to find every road out closed by snow, and one set of footprints leading into the woods and none coming back. Write 300–500 words. Vibe: hushed and white. Anchor: the footprints are the only clue; no one says what they fear. Aim: dread that arrives softly.',
    '**The Shop After Hours** — A clerk stays late to close up and hears someone moving in the back room. Write 250–450 words. Vibe: creeping, patient suspense. Anchor: keep the clerk in one spot the whole time; everything comes through sound and shadow. Aim: the moment before the door opens.',
    // Place and atmosphere
    '**Closing Night** — A diner that has been open every day for forty years serves its last customers. Write 400–700 words. Vibe: warm, a little sad, funny in places. Anchor: the scene lasts exactly one hour, from the last seating to the lights going off. Aim: the reader feels like a regular.',
    '**Fog Crossing** — Write a ferry crossing in fog so thick the captain navigates by the horn alone. 250–400 words. Vibe: muffled, suspended, dreamlike. Anchor: no visual detail farther than ten feet away. Aim: the reader feels the fog on their skin.',
    '**The Greenhouse in January** — Someone keeps a greenhouse alive through a hard winter. Write 300–500 words. Vibe: stubborn warmth against the cold. Anchor: name at least five specific plants, and let each reveal something about the keeper. Aim: a character portrait drawn through what they care for.',
    '**Heat Wave** — Write a city street on the hottest day of the year, from dawn to midnight, in five short sections. Vibe: sticky, loud, restless. Anchor: each section is 60–100 words and happens at a different hour. Aim: the heat feels like a character.',
    '**Off-Season** — A beach town in February, when every shop is shuttered but one. Write 300–500 words about whoever keeps it open. Vibe: salt, wind, and loneliness that isn’t unhappy. Anchor: no one in the scene talks about summer. Aim: a place the reader wants to visit only in winter.',
    '**The Attic** — Describe an attic full of a family’s saved things, from the point of view of the house. 250–400 words. Vibe: patient, affectionate, a little ancient. Anchor: the house can only notice, not act. Aim: the reader sees a family through what it kept.',
    '**Power Outage** — A hotel lobby during a blackout, lit only by phones and one candle at the front desk. Write 400–600 words. Vibe: strangers made briefly intimate. Anchor: at least four guests, each given one line of dialogue. Aim: when the lights come back, the reader is sorry.',
    '**First Rain** — Write the first night of rain after a long drought, on one porch. 200–350 words. Vibe: relief so big it’s almost grief. Anchor: the smell comes first; don’t mention the rain until the second paragraph. Aim: the reader exhales.',
    // People and relationships
    '**Two Coffees** — Two people who used to be close run into each other in line at a café. Write the conversation in 500–800 words. Vibe: polite on the surface, loaded underneath. Anchor: neither mentions what happened between them. Aim: the reader figures out what happened anyway.',
    '**The Recipe Card** — Write a scene built around a handwritten recipe card passed down in a family. 300–600 words. Vibe: warm, specific, bittersweet. Anchor: quote the card itself, stains and cross-outs included. Aim: the recipe carries a whole relationship.',
    '**Driving Lesson** — A parent teaches a teenager to drive. Write 400–700 words. Vibe: tense, funny, tender. Anchor: the whole scene happens inside the car. Aim: one small moment where the roles quietly reverse.',
    '**The Apology** — Write a letter of apology that the writer never sends. 300–500 words. Vibe: raw and plain-spoken. Anchor: the writer keeps almost saying the real thing, then stepping around it. Aim: by the end the reader knows what they did.',
    '**Night Shift** — Two coworkers on an overnight shift share the quietest hour. Write 400–700 words. Vibe: tired, funny, oddly close. Anchor: they talk about small things only. Aim: something big passes between them without being said.',
    '**Moving Day** — Someone packs up the house they grew up in. Write 400–600 words. Vibe: brisk on the surface, overwhelmed underneath. Anchor: tell it through what they keep, what they give away and one thing they can’t decide about. Aim: the undecided object stays with the reader.',
    '**The Understudy** — An understudy finally goes on, the night the lead can’t. Write 500–800 words. Vibe: nerves and electricity. Anchor: start five minutes before curtain and end at the first line spoken. Aim: the reader is holding their breath.',
    '**Wrong Number** — Two strangers keep texting after a wrong number. Write their story in 20–40 short texts. Vibe: light, then surprisingly deep. Anchor: text messages only, with times; no narration. Aim: the reader wants them to meet, or hopes they never do.',
    // Short forms and constraints
    '**One Hundred Words** — Write a complete story in exactly 100 words. Vibe: your choice, but commit to it. Anchor: a beginning, a turn and an ending; count every word. Aim: a story that feels bigger than its size.',
    '**Six Objects** — Write a story that passes through six objects: a key, a ticket stub, a jar of buttons, a photograph, a coat and a bell. 400–700 words. Vibe: gentle, connected, a little magical. Anchor: each object changes hands at least once. Aim: the reader sees how the objects link people.',
    '**Second Person** — Write a scene in second person (“you”) about a morning that turns out to be the last ordinary one for a while. 300–500 words. Vibe: intimate and quietly ominous. Anchor: the change is only hinted at in the final sentence. Aim: the reader rereads the first line.',
    '**Backwards** — Write a short story in reverse, starting with the ending and ending with the first moment. 400–700 words in five to eight scenes. Vibe: mysterious, then clarifying. Anchor: each scene answers a question the one before it raised. Aim: the first moment lands like a reveal.',
    '**One Sentence** — Write a whole scene as one long sentence, 150–300 words. Vibe: breathless. Anchor: no full stops until the very end; use commas, dashes and “and.” Aim: the reader feels the rush.',
    '**Only Dialogue** — Write a scene between two people, entirely in dialogue, 400–600 words. Vibe: tension rising. Anchor: no tags beyond “said” and no description at all. Aim: the reader can see the room anyway.',
    '**Postcards** — Write a story told in five postcards from the same traveler, each 60–100 words. Vibe: bright, then cracking. Anchor: we never see the replies. Aim: the reader knows exactly why the trip went wrong.',
    '**The List** — Write a story in the form of a to-do list, with items crossed out, added and rewritten over a week. Vibe: funny, then quietly devastating. Anchor: list items only, plus tiny notes in the margin. Aim: the reader feels a life change through errands.',
    // Speculative and strange
    '**The Lost and Found** — A lost-and-found office holds things people lost that were never objects: a sense of direction, an accent, a summer. Write 300–600 words. Vibe: whimsical, melancholy. Anchor: follow one clerk through one visitor’s claim. Aim: an ending that feels true even though it’s impossible.',
    '**Weather Report** — In a town where the weather follows the mayor’s mood, the forecast is suddenly grim. Write 400–700 words. Vibe: small-town comedy with a heart. Anchor: include one actual weather report, word for word. Aim: the reader roots for the mayor.',
    '**The Map Shop** — A shop sells maps of places that don’t exist yet. Someone buys one. Write 400–700 words. Vibe: curious and quietly wondrous. Anchor: describe the map in detail before we learn what it’s for. Aim: the reader wants a map of their own.',
    '**The Stopped Clock** — Every clock in a house stopped at the same minute years ago, and no one will reset them. Write 300–500 words. Vibe: gothic, hushed. Anchor: a visitor tries to wind one. Aim: the reader learns what happened at that minute, and wishes they hadn’t.',
    '**Last Light** — Write about the final night before the sun stops rising, from someone who has decided to spend it ordinarily. 400–700 words. Vibe: calm, luminous, sad. Anchor: nothing dramatic happens; they do chores. Aim: the ordinariness breaks the reader’s heart.',
    '**The Night Library** — A library that is only open between midnight and 4 a.m. has one rule. Write 300–600 words. Vibe: hushed and enchanted. Anchor: say the rule in the first paragraph; someone breaks it by the end. Aim: the consequence feels fair and strange.',
    '**Echo** — Someone discovers that a canyon echoes back things they haven’t said yet. Write 300–500 words. Vibe: eerie and wondering. Anchor: we hear three echoes, each more personal. Aim: the last echo changes what they do next.',
    // Memory and personal essays
    '**The Kitchen Table** — Write a personal essay about a table you’ve eaten at, argued at or worked at. 600–1,000 words. Vibe: reflective and specific. Anchor: begin with one physical mark on the table and return to it at the end. Aim: the table holds a stretch of your life.',
    '**A Smell I Remember** — Write a short essay that begins with a smell and follows where it takes you. 400–700 words. Vibe: drifting, sensory, honest. Anchor: go back to the smell three times, each time changed. Aim: the reader remembers a smell of their own.',
    '**The First Job** — Write an essay about your first job and what it taught you that you didn’t notice at the time. 500–900 words. Vibe: funny, fond, a little rueful. Anchor: include one boss, one customer and one uniform. Aim: a small lesson that turns out to be big.',
    '**What I Got Wrong** — Write an essay about something you believed strongly for years and later changed your mind about. 600–1,000 words. Vibe: candid, without self-punishment. Anchor: pinpoint the exact moment the belief cracked. Aim: the reader trusts you more for having been wrong.',
    '**A Place That’s Gone** — Write about a place from your life that no longer exists: a store, a house, a field. 500–900 words. Vibe: elegiac but not gloomy. Anchor: walk the reader through it room by room, or step by step. Aim: the place exists again for as long as they’re reading.',
    '**The Photograph** — Choose a real photograph of yourself you’ve never liked and write about it. 400–800 words. Vibe: wry and tender. Anchor: describe exactly what’s in the frame before you say how you feel. Aim: by the end you like it a little more.',
    '**Rules I Live By** — Write an essay built around five small personal rules, each earned by a story. 600–1,000 words. Vibe: warm, a bit funny, grounded. Anchor: each rule is one sentence, followed by the story that made it. Aim: the reader borrows at least one.',
    '**Letter to a Younger Me** — Write to yourself at a specific age, on a specific day. 400–700 words. Vibe: kind and honest, not preachy. Anchor: name the exact day and what you were worried about. Aim: advice that’s surprising, not obvious.',
    // Craft exercises
    '**Show the Anger** — Write a scene of someone furious who never raises their voice or says how they feel. 300–500 words. Vibe: controlled pressure. Anchor: the anger lives only in actions and objects. Aim: the reader feels the temperature rise.',
    '**The Unreliable Narrator** — Someone tells us about the night they did nothing wrong. Write 400–700 words. Vibe: charming, then suspicious. Anchor: plant three details that contradict what they claim. Aim: the reader catches the lie before the narrator admits anything.',
    '**Slow Motion** — Take a moment that lasts under ten seconds, like a glass falling or a car door closing, and stretch it to 400 words. Vibe: heightened, vivid. Anchor: no flashbacks; stay inside those seconds. Aim: time feels elastic.',
    '**The Other Side** — Retell a well-known fairy tale from the point of view of the villain’s servant. 500–800 words. Vibe: wry and sympathetic. Anchor: keep every event of the original; change only who is watching. Aim: the reader never hears the story the same way again.',
    '**Five Senses, One Room** — Describe a single room using one sense per paragraph, five paragraphs. 300–500 words. Vibe: immersive. Anchor: sight goes last. Aim: by the time we see the room, we already know it.',
    '**Weather as Mood** — Write the same short scene twice: once in bright sun, once in a storm. 200–300 words each. Vibe: identical events, opposite feelings. Anchor: change only the weather and how the characters notice it. Aim: the reader sees how much setting does.',
    '**Subtext** — Two characters discuss what to have for dinner, but they’re really talking about whether to stay together. Write 400–600 words. Vibe: domestic and taut. Anchor: dinner is the only topic; the relationship is never named. Aim: the reader knows the answer before the characters do.',
    '**Open on Action** — Start a story in the middle of something already happening, with no setup. 400–700 words. Vibe: kinetic. Anchor: the first sentence has a verb in its first five words, and no explanation until the halfway mark. Aim: the reader is hooked before they know why.',
    // Lighter and playful
    '**The Complaint** — Write a formal letter of complaint from a houseplant to its owner. 300–500 words. Vibe: indignant and very polite. Anchor: stay in the voice of formal business letters. Aim: the reader laughs and waters something.',
    '**Tiny Heist** — Plan and pull off a heist of something absurdly small: the last cookie, a parking space, the remote. 500–800 words. Vibe: cinematic, overdramatic, fun. Anchor: use heist tropes: a crew, a plan, a twist. Aim: the stakes feel enormous and ridiculous.',
    '**The Review** — Write a glowing five-star review of an ordinary thing: a paper clip, a Tuesday, a puddle. 250–400 words. Vibe: earnest and over the top. Anchor: include pros, cons and a “would recommend.” Aim: the reader appreciates the thing a little.',
    '**Wrong Genre** — Write a scene of an ordinary chore, like grocery shopping or folding laundry, in the style of a noir detective story. 300–500 words. Vibe: hard-boiled and absurd. Anchor: the narrator treats the chore as a case. Aim: the voice carries the joke all the way through.',
    '**Instruction Manual** — Write the instructions for something that doesn’t have instructions: making a friend, leaving a party, getting over a song. 300–500 words. Vibe: dry, numbered, secretly heartfelt. Anchor: numbered steps and one “Troubleshooting” section. Aim: the last step catches the reader off guard.',
  ],
];
